version: "3"

services:
  sandbox:
    image: "tqtezos/flextesa:20210602"
    command: flobox start

  node:
    image: "ekino/ci-node:14-2021.07.31"
    depends_on:
      - "sandbox"
    volumes:
      - ./:/workspace
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"] # keeps container alive
